### PR TITLE
TH2-4829 - Add more output if error or exception

### PR DESCRIPTION
**Pull request by ConnectDIY**

### CODE REVIEW

**Review by RaevskiySV — APPROVED** [review]

**Comment by ConnectDIY** [comment]
@RaevskiySV I believe that we have to merge this, otherwise we will lose these changes

**Comment by RaevskiySV** [comment]
@ConnectDIY have we tested it?

**Comment by ConnectDIY** [comment]
You removed th2-common==3.9.2.dev4356945780, but it contains required changes for this task

It was tested in the Q*** client project

**Review by RaevskiySV — APPROVED** [review]

**Comment by RaevskiySV** [comment]
@ConnectDIY we've merged this changes into th2-common 3.9.2 release version.

Approved, feel free to merge.

**Pull request merged**
